@BooksAuthorsApi.Api_HostAddress = https://localhost:7289

POST {{BooksAuthorsApi.Api_HostAddress}}/api/authors
Content-Type: application/json

{
  "name": "Isabel Allende",
  "nationality": "Chilean"
}

###

POST {{BooksAuthorsApi.Api_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "The House of the Spirits",
  "authorId": 11,
  "year": 1982
}

###
@id = 11
DELETE {{BooksAuthorsApi.Api_HostAddress}}/api/authors/{{id}}

###
